# Generated by Django 4.0.5 on 2022-06-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='neighborhood',
        ),
        migrations.AddField(
            model_name='business',
            name='neighborhood',
            field=models.ManyToManyField(null=True, related_name='business', to='neighborapp.neighborhood'),
        ),
    ]
