# Generated by Django 4.0.5 on 2022-06-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborapp', '0002_remove_business_neighborhood_business_neighborhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_image',
            field=models.ImageField(default='default.png', upload_to='business/'),
        ),
    ]
