# Generated by Django 4.0.5 on 2022-06-17 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighborapp', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='neighborapp.profile'),
        ),
    ]
