# Generated by Django 4.0.5 on 2022-06-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborapp', '0003_business_business_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='business_image',
            field=models.ImageField(default='default.png', upload_to='hoods/'),
        ),
    ]
