# Generated by Django 4.0.5 on 2022-06-19 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborapp', '0004_neighborhood_business_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighborhood',
            old_name='business_image',
            new_name='hood_profile',
        ),
    ]
