# Generated by Django 4.0.5 on 2022-06-18 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighborapp', '0006_post_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('occupants_count', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='neighborhood',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='neighborapp.neighborhood'),
        ),
    ]
