# Generated by Django 4.0.5 on 2022-06-18 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighborapp', '0007_neighborhood_profile_neighborhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='neighborhood',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='business', to='neighborapp.neighborhood'),
        ),
    ]
