# Generated by Django 4.0.5 on 2022-06-18 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborapp', '0008_business_neighborhood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='neighborhood',
        ),
        migrations.DeleteModel(
            name='Neighborhood',
        ),
    ]
