# Generated by Django 4.0.5 on 2022-06-18 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighborapp', '0010_neighborhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='neighborhood',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business', to='neighborapp.neighborhood'),
        ),
        migrations.AddField(
            model_name='profile',
            name='neighborhood',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='neighborapp.neighborhood'),
        ),
    ]
