# Generated by Django 4.0.5 on 2022-06-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborapp', '0011_business_neighborhood_profile_neighborhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_email',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='business_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='health_contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='police_contact',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='second_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
