# Generated by Django 4.0.5 on 2022-06-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborapp', '0012_business_business_email_business_business_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
